CREATE EXTENSION pgcrypto;

CREATE TABLE example (
  pk BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  amount NUMERIC NOT NULL,
  date_on TIMESTAMPTZ NOT NULL
);
